name: Is requests a standard library of Python 3?

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: python3 -c 'import requests; print(1)'
