name: Is requests a standard library of Python 3?

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: df -h
      - run: mount | column -t
      - run: pwd
